services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todoapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todoapp"]
      interval: 5s
      timeout: 5s
      retries: 5
  logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /todo-app-aws/containers
        awslogs-stream: db
    

  server:
    image: 782624259096.dkr.ecr.ap-south-1.amazonaws.com/todo-app-server:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.docker
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /todo-app-aws/containers
        awslogs-stream: server

  client:
    image: 782624259096.dkr.ecr.ap-south-1.amazonaws.com/todo-app-client:latest
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - server
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /todo-app-aws/containers
        awslogs-stream: client

volumes:
  pgdata: